name: "Copy To Branches Action"
author: "Ray Villalobos"
description: "Copies a number files from the a 'key' branch to other branches on repository."
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "-p"
branding:
  icon: "git-branch"
  color: "red"
